# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b0ff5fed9e54d8072bed5bb2b117c194b079225102a79cac6859ff527d4a01df779971015a5113ff3c6617f85f08cf1bf42cadfb6703d697327a52ee75b7451

test:
  secret_key_base: fff66792455e3ff8c89227df86380ad5742266507f14bbfe9ffecdd6fbc9f8eb6b2790ba11d1274c44086188776d85f12833b5c53ac71542f10612d343b7782e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
